// Code generated by "stringer -type=PageIndex"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[pgStart - -1]
	_ = x[pgIntro-1]
	_ = x[pgSource-2]
	_ = x[pgFilter-3]
	_ = x[pgLoad-4]
	_ = x[pgTarget-5]
	_ = x[pgSave-6]
	_ = x[pgSMS-7]
	_ = x[pgUpload-8]
	_ = x[pgFinish-9]
	_ = x[pgExit-10]
}

const (
	_PageIndex_name_0 = "pgStart"
	_PageIndex_name_1 = "pgIntropgSourcepgFilterpgLoadpgTargetpgSavepgSMSpgUploadpgFinishpgExit"
)

var (
	_PageIndex_index_1 = [...]uint8{0, 7, 15, 23, 29, 37, 43, 48, 56, 64, 70}
)

func (i PageIndex) String() string {
	switch {
	case i == -1:
		return _PageIndex_name_0
	case 1 <= i && i <= 10:
		i -= 1
		return _PageIndex_name_1[_PageIndex_index_1[i]:_PageIndex_index_1[i+1]]
	default:
		return "PageIndex(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
