#on: [push]
on:
  push:
    tags:
    - '*'
permissions:
  contents: write
  packages: write
jobs:
  Build-Release-Windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: List files
        run: |
          Get-ChildItem -Recurse | Format-Table -Property Mode, LastWriteTime, Length, FullName

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.5

      - name: Install Fyne
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Build Win64
        run: fyne package -os windows -icon logo.jpeg

      - name: Archive to ZIP
        run: |
          Compress-Archive -Path QeVR.exe, opengl32.dll -DestinationPath qevr_windows_amd64.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            qevr_windows_amd64.zip
            
  Build-Release-Darwin-amd64:
    runs-on: macos-13
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: List files
        run: ls -lR

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.5

      - name: Install Fyne
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Build Darwin
        run: fyne package -os darwin -name QeVR -icon logo.jpeg

      - name: Archive to ZIP
        run: |
          zip -r qevr_darwin_amd64.zip QeVR.app

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            qevr_darwin_amd64.zip
  
  Build-Release-Darwin-arm64:
    runs-on: flyci-macos-large-latest-m2 #macos-13-xlarge
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: List files
        run: ls -lR

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.5

      - name: Install Fyne
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Build Darwin
        run: fyne package -os darwin -name QeVR -icon logo.jpeg

      - name: Archive to ZIP
        run: |
          zip -r qevr_darwin_amd64.zip QeVR.app

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            qevr_darwin_arm64.zip
    